### PR TITLE
Update to 1.0.0

### PR DESCRIPTION
**Pull request by SilverRainZ**

### CODE REVIEW

**Comment by cpba** [comment]
It failed appdata validation:

https://flathub.org/builds/#/builders/32/builds/15687

```
builddir/files/share/appdata/im.srain.Srain.appdata.xml: FAILED:
• style-invalid         : <caption> is too short [Main];shortest allowed is 5 chars
Validation of files failed
```

But the appdata file looks fine, I'll try to look into it.

**Comment by SilverRainZ** [comment]
@cpba Thanks for pointing out, it seems be fixed.

**Comment by cpba** [comment]
I see you already fixed it here:

https://github.com/SrainApp/srain/commit/57e2adeb1572447b14d23f6417d3b376665a6f25

I was actually looking at the wrong branch, `master` instead of `update_1.0.0`, that's why I thought it was fine.

Congratulations on the release :)

**Comment by SilverRainZ** [comment]
@cpba Thank you!

**Pull request merged**
