### PR TITLE
Update to 1.0.1

### PR DESCRIPTION
**Pull request by SilverRainZ**

### CODE REVIEW

**Comment by SilverRainZ** [comment]
Why https://flathub.org/apps/details/im.srain.Srain is still 1.0.1? @cpba any idea?

**Comment by cpba** [comment]
@SilverRainZ The latest version on flathub also looks like 1.0.0:

srainnot101

I'm not sure what happened. Maybe the build failed somewhere and nobody noticed, I'll try to look into it.

**Comment by cpba** [comment]
@SilverRainZ I triggered a manual build:

https://flathub.org/builds/#/builders/32/builds/17025

It fails with:

`Failed to download sources: module srain: Git commit for branch master is 4ac4c7d41bcee2e785cb8c19f3b79ea6d3c26ef6, but expected 01b3761d172ff57a881cbe759b523b33c7bd8fb0`

This happens because we're specifying both branch and commit, I'll work around it by creating a new PR.

However, this commit didn't exist 4 days ago, so there must be a different problem that I'm not yet seeing.

**Comment by SilverRainZ** [comment]
It seems that buildbot askes the specified commit must be HEAD of specified branche, so we always need a branch for flathub?

**Comment by cpba** [comment]
@SilverRainZ I merged #19 and it seems to have worked.

The build finished without issue and is currently publishing:

https://flathub.org/builds/#/builders/29/builds/14292

**Comment by cpba** [comment]
Good news, 1.0.1 is now live on flathub:

```
flatpak info im.srain.Srain

Srain - Modern IRC client written in GTK.

          ID: im.srain.Srain
         Ref: app/im.srain.Srain/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.1
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 816,1 kB
     Runtime: org.gnome.Platform/x86_64/3.34
         Sdk: org.gnome.Sdk/x86_64/3.34

      Commit: 028f3e6bd8b67a1a788d73fc8977700e5a3cfd7346015252b37701fe6d9531db
      Parent: 265ee854f8a01f1923e92b81a42d84f930b823109cc28a0e28622a2f79c41b4d
     Subject: Don't specify git branch (0e605fb6)
        Date: 2020-03-18 12:13:26 +0000
```

The website still shows 1.0.0, but that usually takes longer.

I still don't know why it failed when you merged on Saturday, but I'm happy as long as it's working now.

**Pull request merged**
